### ISSUE TITLE
[Feature request] New button style: hover button

### ISSUE THREAD

**Issue by zcyzcy88** [todc/todc-bootstrap#182]
It is useful to get clean vision, if we have a lot of buttons.

<img width="110" alt="2017-03-29 22_33_47-google translate" src="https://cloud.githubusercontent.com/assets/15178410/24467894/eb75eb7c-14e8-11e7-813a-4fe4c11a3bdf.png">
<img width="100" alt="2017-03-29 22_33_50-google translate" src="https://cloud.githubusercontent.com/assets/15178410/24467895/ec45c824-14e8-11e7-85ee-e8bedc67a973.png">

**Comment by zcyzcy88** [comment]
It is easily worked on a single button, but `btn-group` suck if use keyboard navigation.
CSS4 `:has()` selector not yet.

```css
.btn-group.btn-hover:not(:hover) .btn,
.btn-hover
{
	border: 1px solid transparent;
	color: #333;
	background: none;
	text-shadow: none;
}
```
