### ISSUE TITLE
-webkit-appearance breaks in chrome

### ISSUE THREAD

**Issue by apoo** [todc/todc-bootstrap#84]
Following line breaks in chrome:

``` css
  -webkit-appearance: none;
```

Its been set in following statement:

``` css
input[type="checkbox"],
input[type="radio"] {
  -webkit-appearance: none;
  appearance: none;
  width: 13px;
  height: 13px;
  background: white;
  border: 1px solid #dcdcdc;
  -webkit-border-radius: 1px;
  -moz-border-radius: 1px;
  border-radius: 1px;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  position: relative;
  box-sizing: content-box \9;
  width: 16px \9;
  height: 16px \9;
  border-width: 0 \9;
}

```

![Checkbox](https://f.cloud.github.com/assets/483000/266471/34dc0a5c-8e02-11e2-9efa-9f4bc547657f.png)

when i remove/uncheck that line in firebug, it shows the check-box.
